### ISSUE TITLE
Recipes Conflict

### ISSUE THREAD

**Issue by NatsumeLS** [HenrikoMagnifico/YaoPack-Issue-Tracker#10]
Adding [NoMoreRecipeConflict](https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict) mod will solve this problems without messing with Minetweaker. <3

It adds a button to switch between all results of a recipe.

**Comment by HenrikoMagnifico** [comment]
Good idea! I'll add it to the next release of the Yao pack.
