### ISSUE TITLE
forestry:crated items causing crashes when looked up in JEI

### ISSUE THREAD

**Issue by NatsumeLS** [HenrikoMagnifico/YaoPack-Issue-Tracker#12]
https://github.com/mezz/JustEnoughItems/issues/1462

Issue only occured when using some shader.
Fixed by downgrading to [jei_1.12.2-4.15.0.268](https://www.curseforge.com/minecraft/mc-mods/jei/files/2682936)

**Comment by HenrikoMagnifico** [comment]
Fixed in the upcoming release of the Yao Pack.
