### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by NatsumeLS** [HenrikoMagnifico/YaoPack-Issue-Tracker#13]
**Recommended**

- [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor)
Significant improvement of lighting engine.
Performance increased at least 2 times on some system.
**Fully compatible with OptiFine.**

- [Surge](https://www.curseforge.com/minecraft/mc-mods/surge)
Improve load time.
**Client side (Will crash on server side)**

- [AI Improvements](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
Replace EntityLookHelper with a more efficient version.

- [HelpFixer](https://www.curseforge.com/minecraft/mc-mods/helpfixer)
Improve `/help` sorting.

- [Treecapitator](https://www.curseforge.com/minecraft/mc-mods/treecapitator-updated)
Trees cutting enhancement with modded trees detection.
**Fix floating trees issue on server**

**Extras**

- [MrCrayfish's Furniture Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
Popular furnitures mod.

- [DiscordSuite](https://www.curseforge.com/minecraft/mc-mods/discordsuite) or [Galacticraft Rich Presence](https://www.curseforge.com/minecraft/mc-mods/galacticraft-rpc)
**DiscordSuite** can display modpack information on Discord profile.
**Galacticraft Rich Presence** show information about the planet, moon or space station a player is visiting on Discord profile.
**Client side**

- [OnlinePictureFrame](https://www.curseforge.com/minecraft/mc-mods/onlinepictureframe)
Allows you to pick any picture of the internet and bring it to minecraft.

- [Ding](https://www.curseforge.com/minecraft/mc-mods/ding)
Plays a configurable sound when Minecraft loads and reaches the Main Menu, or when the world loads when you connect to a server.
**Client side**

**Comment by HenrikoMagnifico** [comment]
I will look into adding some of these mods. Thanks for suggesting them!
