### ISSUE TITLE
Quarry not working

### ISSUE THREAD

**Issue by JurassicJax483** [HenrikoMagnifico/YaoPack-Issue-Tracker#14]
Hi i recently started this modpack and was having alot of fun until i made my quarry. I have done everything right and it just keeps glitching. The miner drill goes and tries to destroy a block and cant then it just stops. PLEASE FIX! thanks Jurassic_Jax

**Comment by HenrikoMagnifico** [comment]
Is this occuring on a Yao Pack server or in single player?

**Comment by JurassicJax483** [comment]
server

**Comment by HenrikoMagnifico** [comment]
It's a server side issue, I have informed the server owner about this issue.
