### ISSUE TITLE
Error Downloading Pack

### ISSUE THREAD

**Issue by Hbibby** [HenrikoMagnifico/YaoPack-Issue-Tracker#15]
Given the following prompt when attempting to download:

Failed to download https://www.dropbox.com/s/6bpnvg1d7fal9rx/Yao%20Pack%203.1.8_rev1.zip?dl=1

Please consult modpack author.

Thanks for help in advance.

**Comment by HenrikoMagnifico** [comment]
Caused by my dropbox account being suspended due to too much traffic. I've reset the links and it should work again.
