### ISSUE TITLE
Yao Pack server not working

### ISSUE THREAD

**Issue by JurassicJax483** [HenrikoMagnifico/YaoPack-Issue-Tracker#16]
Hi i have been playing for the past week and there was an update this morning. Now every time i try to join the server it says( Server Mod Rejections: Pam's Harvest Craft : requires version 1.12.2zb but mod is not found on client) plz fix
Thank you Jurassic Jax

**Comment by HenrikoMagnifico** [comment]
The Yao Pack Revived server had not been updated yet. Issue closed.
