### ISSUE TITLE
Wub Hammer can cause server crash

### ISSUE THREAD

**Issue by NatsumeLS** [HenrikoMagnifico/YaoPack-Issue-Tracker#17]
Crash Report:
https://paste.dimdev.org/owibefexeg.rb

Current work around I'm using:
```
config/Tiny Progressions/Supporters.cfg

"wub juice extras" {
    # Enable Extras? [default: true]
    B:"Tools & Weapons"=false
}
```
Or just ban Wub Hammer on server-side

**Comment by HenrikoMagnifico** [comment]
Thanks for reporting this bug. I'll look into it. If I can not find a solution I will add the proposed change to the next update.
