### ISSUE TITLE
Yao pack not working

### ISSUE THREAD

**Issue by Clockseer** [HenrikoMagnifico/YaoPack-Issue-Tracker#18]
I have downloaded java 64 bit and whenever I click play it will give me a message saying java 12.0.2 might is not supported do you still want to run it and then gives me an option of yes or no if i choose the yes option the technic launcher closes and it tries to run but it fails and starts the technic laucher again. I took a screenshot of the console so if anyone can help please do
![Screenshot (1)](https://user-images.githubusercontent.com/54509673/63654033-8a125a80-c73a-11e9-822c-8343bcc85a1d.png)

**Comment by HenrikoMagnifico** [comment]
Try uninstalling all of Java and re-installing it from here (64-bit offline version): https://java.com/en/download/manual.jsp
