### ISSUE TITLE
Server don't start

### ISSUE THREAD

**Issue by Scheffio** [HenrikoMagnifico/YaoPack-Issue-Tracker#19]
Issue: Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap
(18:27:12,79) Server closed/crashed... restarting!
I have 8gh RAM on my pc

**Comment by HenrikoMagnifico** [comment]
You must install 64-bit Java. Do so from here: https://java.com/en/download/manual.jsp

**Comment by Scheffio** [comment]
I already have

31 авг 2019 г. 10:47 PM пользователь "Henriko Magnifico" <
notifications@github.com> написал:

**Comment by HenrikoMagnifico** [comment]
I need some more information. Are you using Windows 10? Are you using the Yao Pack Server Builder (available on the technic launcher page)? 

Here is a proposed fix for the error, which should hopefully fix the issue either way.

Go to Start → Control Panel → System → Advanced system settings → advanced(tab) → Environment Variables → System Variables → New:

`
Variable name: _JAVA_OPTIONS
Variable value: -Xmx512
`

**Comment by Scheffio** [comment]
Windows 10 = +
Builder = +

31 авг 2019 г. 10:56 PM пользователь "Henriko Magnifico" <
notifications@github.com> написал:
