### ISSUE TITLE
Engine Peat Forestry crash

### ISSUE THREAD

**Issue by knejzu** [HenrikoMagnifico/YaoPack-Issue-Tracker#21]
Hello, I build an Engine Peat from the mod Forestry and the world crashed. How can i solve it? I dont want to lose my world. It still crashes when i start the world. Thank you for your answer.
Here is the report - https://paste.dimdev.org/ujeteluqon.mccrash

**Comment by HenrikoMagnifico** [comment]
Strange issue, if it's still present in the most recent version of Yao Pack please contact the original mod author.
