### ISSUE TITLE
Fatal Error When Connecting to Server

### ISSUE THREAD

**Issue by Treeaza** [HenrikoMagnifico/YaoPack-Issue-Tracker#22]
When attempting to connect to a friend's server (hosted through Aternos) I get the error seen in the screenshot below:

![Screenshot (7)](https://user-images.githubusercontent.com/11872999/64302851-e0b03d80-cf5f-11e9-9495-81e5554c2364.png)

I have tried reinstalling the modpack, redownloading the Technic launcher, and reinstalling Java to no success. Other people have successfully connected, so the issue is somewhere on my end.

**Comment by HenrikoMagnifico** [comment]
Aternos is not supported using the Yao Pack server builder. How have they set up the server?

**Comment by Treeaza** [comment]
They set up the server through the Aternos website, and two other people were able to successfully connect and play.
