### ISSUE TITLE
Aternos not working

### ISSUE THREAD

**Issue by ghebert3** [HenrikoMagnifico/YaoPack-Issue-Tracker#23]
when I try to join my aternos server it doesn't work.. the error that pops up is fatally missing registry this also happens in the yao pack playground.

**Comment by Treeaza** [comment]
This is the same issue I've had as well, at the same time judging from when we both posted it.

**Comment by HenrikoMagnifico** [comment]
Old issue caused by lack of RAM allocated on Aternos side, has since been fixed.
