### ISSUE TITLE
Error downloading a file for the following pack: Yoa pack

### ISSUE THREAD

**Issue by wistful-jpg** [HenrikoMagnifico/YaoPack-Issue-Tracker#26]
![WillnotDownload](https://user-images.githubusercontent.com/62160464/76665571-c08cb700-655e-11ea-8c28-3b95a204399c.PNG)

**This issue has happened before **

> https://github.com/HenrikoMagnifico/YaoPack-Issue-Tracker/issues/25

**Comment by tupls** [comment]
Download it manually and it should fix it

**Comment by HenrikoMagnifico** [comment]
This is usually due to the file server being overloaded. Wait a few minutes and try again or use the manual download. I also heard that someone managed to fix it by temporarily disabling their firewall, but I can't confirm this.
