### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by weirwolf20** [HenrikoMagnifico/YaoPack-Issue-Tracker#28]
Everytime i go to the aether its fine with the resource pack but when i go to twilight forest the sky is gone weird with the resource pack is there any specific pack i need to work with all dimensions?

**Comment by HenrikoMagnifico** [comment]
Is the issue still occuring after disabling any applied Shaders in the shaders menu? _Video Settings > Shaders_

**Comment by HenrikoMagnifico** [comment]
Fixed in Yao Pack 3.2.1. Issue closed.
