### ISSUE TITLE
Game is crashing when using JEI search bar

### ISSUE THREAD

**Issue by scars600** [HenrikoMagnifico/YaoPack-Issue-Tracker#29]
The game will crash when I am attempting to look up the letters "wu", and I have already tried to uninstall and reinstall both the modpack and java x64 offline. I have 7 GB of RAM allotted through the technic launcher as well, and crash logs are below.

[crash-2020-05-22_14.03.53-client.txt](https://github.com/HenrikoMagnifico/YaoPack-Issue-Tracker/files/4669961/crash-2020-05-22_14.03.53-client.txt)

**Comment by HenrikoMagnifico** [comment]
Cannot replicate in my system. Please try updating Yao Pack to the latest version and remember to **only** allocate **half** of your total system ram to Technic Launcher. Less is more, sometimes.
