### ISSUE TITLE
I made a space station and was sent flying off it

### ISSUE THREAD

**Issue by whathtehell** [HenrikoMagnifico/YaoPack-Issue-Tracker#3]
I made an earth space station and was immediately thrown around and sent shooting out one side of the station. ?????????? my rocket is up there so I have to make a new one......

**Comment by HenrikoMagnifico** [comment]
I am not sure what is causing this. However, it seems to be intentional behaviour, see this thread; https://github.com/micdoodle8/Galacticraft/issues/1555
