### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by Boose101** [HenrikoMagnifico/YaoPack-Issue-Tracker#31]
The graphics of the game are in my bottom right-hand corner, but the controls are where they should be. Whenever I have to click quit it's not where the graphic is but where it should be if it was working.

**Comment by HenrikoMagnifico** [comment]
I need more information. Share your hardware specifications (Processor, graphics card, RAM, operating system).

**Comment by Boose101** [comment]
iMac Pro(2017)
Processor 3.2 GHz 8-Core Intel Xeon W
Memory 32 GB 2666 MHz DDR4
Graphics Radeon Pro Vega 56 8 GB

**Comment by Boose101** [comment]
I can send more detailed specs if you need them.

**Comment by HenrikoMagnifico** [comment]
Looking into the issue! In the meanwhile, deleting your "shaderpacks" folder inside your Yao Pack directory will fix the crash.
