### ISSUE TITLE
Really Slow Download

### ISSUE THREAD

**Issue by dzkm** [HenrikoMagnifico/YaoPack-Issue-Tracker#33]
Hello,

It seems that the developer recently changed the way it hosts the modpack to a self-hosted server. This has brought the download speed to a halt, going as high as 0.1MB/s (100KB/s) and as low as 0.05MB/s (50KB/s).

Here's some screenshots with proof that the download is being slow and my internet is pretty decent even to the region where its being hosted on: 

Download speed while writing issue:
![image](https://user-images.githubusercontent.com/13489382/83946597-3dd76900-a7e8-11ea-8812-aec9a2b70b55.png)

Internet speed to closest server (Speedtest method):
![image](https://user-images.githubusercontent.com/13489382/83946738-0f0dc280-a7e9-11ea-9298-b2b90d71c271.png)

Internet speed to supposed host region (Speedtest method):
![image](https://user-images.githubusercontent.com/13489382/83946758-1f25a200-a7e9-11ea-9014-59cad32b4a2b.png)

I recommend making a mirror available when the server is having bandwidth issues.

**Comment by HenrikoMagnifico** [comment]
Yao Pack downloads are limited to 10MB/s total for all concurrent clients that are downloading it. The more people are downloading Yao Pack, the slower it is.
