### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by MugenNoRyu** [HenrikoMagnifico/YaoPack-Issue-Tracker#34]
When switching tabs on the advancements a error occurs, while playing through getting the achievements  this can somewhat be solved by leaving the world and joining back.
[crash-2020-06-18_22.26.34-server.txt](https://github.com/HenrikoMagnifico/YaoPack-Issue-Tracker/files/4802147/crash-2020-06-18_22.26.34-server.txt)

**Comment by HenrikoMagnifico** [comment]
Seems to be fixed in the most recent version!
