### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by LuckPlays** [HenrikoMagnifico/YaoPack-Issue-Tracker#35]
when I try to install modpack, it gives an error 
"Error downloading a file to the following modpack: Yao Pack
Failed to download http://bitgen.yao.cl:8080/yp3.2.2b.zip
Please consult the author of this modpack."

**Comment by HenrikoMagnifico** [comment]
Do you still have this issue?

**Comment by LuckPlays** [comment]
I'm not having this problem anymore.

**Comment by Foulerharbor8** [comment]
im having the same problem, is there a fix or should i wait for the author to fix it?

**Comment by HenrikoMagnifico** [comment]
Solved.
