### ISSUE TITLE
Launching Problem

### ISSUE THREAD

**Issue by mitalss** [HenrikoMagnifico/YaoPack-Issue-Tracker#36]
I want to play on MacOS but every time I load up the game, it instantly crashes and I tried fixing the ram, fixing the java, deleting and redownloading it and nothing seems to work.

**Comment by HenrikoMagnifico** [comment]
Looking into the issue! In the meanwhile, deleting your "shaderpacks" folder inside your Yao Pack directory will fix the crash.
