### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by papabear27** [HenrikoMagnifico/YaoPack-Issue-Tracker#38]
![Untitled](https://user-images.githubusercontent.com/71609256/93721085-2a5fcc00-fb53-11ea-9b3a-7aff71e2ffaf.png)
This keeps coming up when downloading. I waited awhile to try it again the next day, same issue. I don't know what/how to "download manually" because I'm a noob

**Comment by HenrikoMagnifico** [comment]
Fixed.
