### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AstromanGaming** [HenrikoMagnifico/YaoPack-Issue-Tracker#5]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2019-04-01 07:16:22 EDT
Description: Updating screen events

java.lang.NullPointerException
    at com.gendeathrow.mpbasic.client.gui.GuiInfoPanel.mouseClicked(GuiInfoPanel.java:234)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['xXSamBelangerXx'/0, l='MpServer', x=-107.50, y=69.00, z=256.50]]
  Chunk stats: MultiplayerChunkCache: 44, 44
  Level seed: 0
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-112,64,256), Chunk: (at 0,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 6819 game time, 6819 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 38 total; [EntityAncientGolem['Ancient Golem'/1, l='MpServer', x=-113.50, y=19.00, z=238.00], EntityItem['item.tile.mushroom8'/2, l='MpServer', x=-113.27, y=19.00, z=225.13], EntityAncientGolem['Ancient Golem'/3, l='MpServer', x=-145.50, y=13.00, z=254.00], EntitySquid['Pieuvre'/4, l='MpServer', x=-102.50, y=58.00, z=282.50], EntitySquid['Pieuvre'/5, l='MpServer', x=-106.50, y=58.00, z=280.50], EntitySquid['Pieuvre'/6, l='MpServer', x=-104.50, y=58.00, z=282.50], EntitySquid['Pieuvre'/7, l='MpServer', x=-106.50, y=58.00, z=283.50], EntitySkeleton['Squelette'/71, l='MpServer', x=-75.50, y=36.00, z=237.50], EntitySquid['Pieuvre'/8, l='MpServer', x=-122.50, y=62.00, z=279.50], EntitySkeleton['Squelette'/72, l='MpServer', x=-75.50, y=36.00, z=235.50], EntityCow['Vache'/9, l='MpServer', x=-139.50, y=71.00, z=237.50], EntitySkeleton['Squelette'/73, l='MpServer', x=-78.50, y=36.00, z=235.50], EntityCow['Vache'/10, l='MpServer', x=-139.50, y=73.00, z=236.50], GCEntityClientPlayerMP['xXSamBelangerXx'/0, l='MpServer', x=-107.50, y=69.00, z=256.50], EntityCow['Vache'/11, l='MpServer', x=-139.50, y=73.00, z=235.50], EntityZombie['Zombie'/75, l='MpServer', x=-74.50, y=36.00, z=233.50], EntityCow['Vache'/12, l='MpServer', x=-137.50, y=70.00, z=237.50], EntityItem['item.item.string'/17, l='MpServer', x=-142.73, y=23.00, z=286.22], EntityPig['Cochon'/81, l='MpServer', x=-49.50, y=63.00, z=271.50], EntityItem['item.tile.mushroom.glowshroom'/18, l='MpServer', x=-147.88, y=22.00, z=281.13], EntityItem['item.item.string'/19, l='MpServer', x=-137.45, y=22.00, z=279.72], EntityPig['Cochon'/83, l='MpServer', x=-48.50, y=63.00, z=273.50], EntityItem['item.item.string'/20, l='MpServer', x=-135.59, y=22.00, z=280.59], EntityPig['Cochon'/84, l='MpServer', x=-51.50, y=63.00, z=272.50], EntitySquid['Pieuvre'/24, l='MpServer', x=-108.50, y=59.00, z=279.50], EntitySpider['Araignée'/29, l='MpServer', x=-128.50, y=21.00, z=273.50], EntityCreeper['Creeper'/30, l='MpServer', x=-130.50, y=21.00, z=273.50], EntitySheep['Mouton'/99, l='MpServer', x=-102.50, y=65.00, z=318.50], EntitySheep['Mouton'/100, l='MpServer', x=-101.50, y=65.00, z=317.50], EntitySheep['Mouton'/101, l='MpServer', x=-101.50, y=65.00, z=317.50], EntitySheep['Mouton'/102, l='MpServer', x=-98.50, y=65.00, z=319.50], EntityHorse['Cheval'/103, l='MpServer', x=-102.50, y=65.00, z=312.50], EntityHorse['Cheval'/104, l='MpServer', x=-101.50, y=65.00, z=312.50], EntityPig['Cochon'/50, l='MpServer', x=-158.50, y=69.00, z=276.50], EntityPig['Cochon'/51, l='MpServer', x=-157.50, y=69.00, z=275.50], EntityPig['Cochon'/52, l='MpServer', x=-158.50, y=70.00, z=274.50], EntityCreeper['Creeper'/62, l='MpServer', x=-95.50, y=48.00, z=282.50], EntityCreeper['Creeper'/63, l='MpServer', x=-96.50, y=48.00, z=281.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6373222736 bytes (6077 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 5 total; -Xms8192m -Xmx8192m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 105
  FML: MCP 9.42 Powered by Forge 14.23.5.2784 Optifine OptiFine_1.12.2_HD_U_E3 123 mods loaded, 123 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version                      | Source                                              | Signature                                |
       |:------ |:--------------------------------- |:---------------------------- |:--------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2                       | minecraft.jar                                       | None                                     |
       | LCHIJA | mcp                               | 9.42                         | minecraft.jar                                       | None                                     |
       | LCHIJA | FML                               | 8.0.99.99                    | modpack.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                             | 14.23.5.2784                 | modpack.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | micdoodlecore                     |                              | minecraft.jar                                       | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4                        | minecraft.jar                                       | None                                     |
       | LCHIJA | opencomputers|core                | 1.7.2.67                     | minecraft.jar                                       | None                                     |
       | LCHIJA | orbis_api                         | 0.1.0                        | orbis_api-0.1.0.jar                                 | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | aether                            | 0.1.1                        | aether_ii-0.1.1-universal.jar                       | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | antiqueatlas                      | 4.4.9                        | antiqueatlas-1.12.2-4.4.9.jar                       | None                                     |
       | LCHIJA | antiqueatlasoverlay               | 1.2                          | antiqueatlas-1.12.2-4.4.9.jar                       | None                                     |
       | LCHIJA | examplemod                        | 1.0                          | antiqueatlas-1.12.2-4.4.9.jar                       | None                                     |
       | LCHIJA | appliedenergistics2               | rv6-stable-3                 | appliedenergistics2-rv6-stable-3.jar                | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | aroma1997core                     | 2.0.0.2.b164                 | Aroma1997Core-1.12.2-2.0.0.2.b164.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | aroma1997sdimension               | 2.0.0.2.b89                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | psi                               | r1.1-59                      | Psi-r1.1-59.jar                                     | None                                     |
       | LCHIJA | jei                               | 4.13.1.220                   | jei_1.12.2-4.13.1.220.jar                           | None                                     |
       | LCHIJA | quark                             | r1.5-145                     | Quark-r1.5-145.jar                                  | None                                     |
       | LCHIJA | autoreglib                        | 1.3-24                       | AutoRegLib-1.3-24.jar                               | None                                     |
       | LCHIJA | baubles                           | 1.5.2                        | Baubles-1.12-1.5.2.jar                              | None                                     |
       | LCHIJA | betteradvancements                | 0.0.14.66                    | BetterAdvancements-1.12.2-0.0.14.66.jar             | None                                     |
       | LCHIJA | betterbuilderswands               | 0.12.1                       | BetterBuildersWands-1.12.2-0.12.1.254+27f21b9.jar   | None                                     |
       | LCHIJA | biomesoplenty                     | 7.0.1.2425                   | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar       | None                                     |
       | LCHIJA | guideapi                          | 1.12-2.1.7-62                | Guide-API-1.12-2.1.7-62.jar                         | None                                     |
       | LCHIJA | bloodmagic                        | 1.12.2-2.3.3-101             | BloodMagic-1.12.2-2.3.3-101.jar                     | None                                     |
       | LCHIJA | bloodmoon                         | 1.5.3                        | Bloodmoon-MC1.12.2-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | blur                              | 1.0.4-14                     | Blur-1.0.4-14.jar                                   | None                                     |
       | LCHIJA | botania                           | r1.10-357                    | Botania+r1.10-357.jar                               | None                                     |
       | LCHIJA | buildcraftlib                     | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcraftcore                    | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcraftbuilders                | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcrafttransport               | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcraftsilicon                 | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcraftenergy                  | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | ic2                               | 2.8.111-ex112                | industrialcraft-2-2.8.111-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | forestry                          | 5.8.2.356                    | forestry_1.12.2-5.8.2.356.jar                       | None                                     |
       | LCHIJA | buildcraftcompat                  | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcraftfactory                 | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | buildcraftrobotics                | 7.99.22                      | buildcraft-all-7.99.22.jar                          | None                                     |
       | LCHIJA | ctm                               | MC1.12.2-0.3.2.20            | CTM-MC1.12.2-0.3.2.20.jar                           | None                                     |
       | LCHIJA | chisel                            | MC1.12.2-0.2.1.35            | Chisel-MC1.12.2-0.2.1.35.jar                        | None                                     |
       | LCHIJA | classiccombat                     | 1.0.0                        | ClassicCombat-1.12-1.0.0.jar                        | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.2.353                    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux                      | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.1                        | CoFHCore-1.12.2-4.6.1.22-universal.jar              | None                                     |
       | LCHIJA | cofhworld                         | 1.3.0                        | CoFHWorld-1.12.2-1.3.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cookingforblockheads              | 6.4.69                       | CookingForBlockheads_1.12.2-6.4.69.jar              | None                                     |
       | LCHIJA | extendedrenderer                  | v1.0                         | coroutil-1.12.1-1.2.13.jar                          | None                                     |
       | LCHIJA | coroutil                          | 1.12.1-1.2.13                | coroutil-1.12.1-1.2.13.jar                          | None                                     |
       | LCHIJA | configmod                         | v1.0                         | coroutil-1.12.1-1.2.13.jar                          | None                                     |
       | LCHIJA | cxlibrary                         | 1.6.1                        | cxlibrary-1.12.1-1.6.1.jar                          | None                                     |
       | LCHIJA | diethopper                        | 1.1                          | diethopper-1.1.jar                                  | None                                     |
       | LCHIJA | ebwizardry                        | 4.1.4                        | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar      | None                                     |
       | LCHIJA | embers                            | 1.12                         | EmbersRekindled-1.12.jar                            | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.45                | EnderCore-1.12.2-0.5.45.jar                         | None                                     |
       | LCHIJA | thermalfoundation                 | 2.6.1                        | ThermalFoundation-1.12.2-2.6.1.22-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                  | 5.5.2                        | ThermalExpansion-1.12.2-5.5.2.39-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                           | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderiobase                       | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderioconduits                   | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | opencomputers                     | 1.7.2.67                     | OpenComputers-MC1.12.2-1.7.2.67.jar                 | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | mantle                            | 1.12-1.3.3.39                | Mantle-1.12-1.3.3.39.jar                            | None                                     |
       | LCHIJA | twilightforest                    | 3.8.689                      | twilightforest-1.12.2-3.8.689-universal.jar         | None                                     |
       | LCHIJA | tconstruct                        | 1.12.2-2.11.0.106            | TConstruct-1.12.2-2.11.0.106.jar                    | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | ftblib                            | 5.4.1.86                     | FTBLib-5.4.1.86.jar                                 | None                                     |
       | LCHIJA | enderiomachines                   | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | enderiopowertools                 | 5.0.39                       | EnderIO-1.12.2-5.0.39.jar                           | None                                     |
       | LCHIJA | energyconverters                  | 1.2.1.11                     | energyconverters_1.12.2-1.2.1.11.jar                | None                                     |
       | LCHIJA | extrautils2                       | 1.0                          | extrautils2-1.12-1.9.8.jar                          | None                                     |
       | LCHIJA | foamfix                           | 0.10.3-1.12.2                | foamfix-0.10.3-1.12.2.jar                           | None                                     |
       | LCHIJA | forgemultipartcbe                 | 2.6.0.79                     | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe                     | 2.6.0.79                     | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | None                                     |
       | LCHIJA | minecraftmultipartcbe             | 2.6.0.79                     | ForgeMultipart-1.12.2-2.6.0.79-universal.jar        | None                                     |
       | LCHIJA | ftbutilities                      | 5.4.0.84                     | FTBUtilities-5.4.0.84.jar                           | None                                     |
       | LCHIJA | galacticraftcore                  | 4.0.1.181                    | GalacticraftCore-1.12.2-4.0.1.181.jar               | None                                     |
       | LCHIJA | galacticraftplanets               | 4.0.1.181                    | Galacticraft-Planets-1.12.2-4.0.1.181.jar           | None                                     |
       | LCHIJA | gravelminer                       | 6.1.2                        | GravelMiner_1.12.1-6.1.2.jar                        | None                                     |
       | LCHIJA | hopperducts                       | 1.5                          | hopperducts-mc1.12-1.5.jar                          | None                                     |
       | LCHIJA | waila                             | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
       | LCHIJA | inventorytweaks                   | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest                         | 1.12.2-7.0.52.837            | ironchest-1.12.2-7.0.52.837.jar                     | None                                     |
       | LCHIJA | itlt                              | 1.0.0                        | itlt-1.12-1.0.0.jar                                 | None                                     |
       | LCHIJA | harvestcraft                      | 1.12.2z                      | Pam's+HarvestCraft+1.12.2za.jar                     | None                                     |
       | LCHIJA | jehc                              | 1.12.2                       | JEHC-1.12.2-1.6.2.0.jar                             | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                         | None                                     |
       | LCHIJA | jrftl                             | 1.1                          | JRFTL[1.12.2]-1.1.jar                               | None                                     |
       | LCHIJA | jeresources                       | 0.8.10.50                    | JustEnoughResources-1.12.2-0.8.10.50.jar            | None                                     |
       | LCHIJA | kleeslabs                         | 5.4.11                       | KleeSlabs_1.12.2-5.4.11.jar                         | None                                     |
       | LCHIJA | lex                               | 1.0.8                        | LibEx-1.12.2-1.0.8.jar                              | None                                     |
       | LCHIJA | llor                              | 1.1.6-mc1.12.2               | LLOverlayReloaded-1.1.6-mc1.12.2.jar                | None                                     |
       | LCHIJA | mcmultipart                       | 2.5.3                        | MCMultiPart-2.5.3.jar                               | None                                     |
       | LCHIJA | mekanism                          | 1.12.2-9.4.13.349            | Mekanism-1.12.2-9.4.13.349.jar                      | None                                     |
       | LCHIJA | mekanismgenerators                | 9.4.11                       | MekanismGenerators-1.12.2-9.4.13.349.jar            | None                                     |
       | LCHIJA | mekanismtools                     | 9.4.11                       | MekanismTools-1.12.2-9.4.13.349.jar                 | None                                     |
       | LCHIJA | modularforcefieldsystem           | 3.0.1                        | MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar                | None                                     |
       | LCHIJA | numina                            | 1.10.0                       | ModularPowersuits-1.12.2-0.7.0.035.jar              | None                                     |
       | LCHIJA | tesla                             | 1.0.63                       | Tesla-1.12.2-1.0.63.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | powersuits                        | 1.12.2-0.7.0.035             | ModularPowersuits-1.12.2-0.7.0.035.jar              | None                                     |
       | LCHIJA | moreplanets                       | 2.0.17                       | More-Planets-1.12.2-2.0.17-GC181.jar                | b3468b224a74e296555ad7efeb35f482e6f445de |
       | LCHIJA | morpheus                          | 1.12-3.3.2                   | Morpheus-1.12-3.3.2.jar                             | None                                     |
       | LCHIJA | mputils                           | 1.5.6                        | MPUtils-1.12.2-1.5.6.jar                            | None                                     |
       | LCHIJA | mpbasic                           | 1.4.7                        | mpbasic-1.12.2-1.4.8.jar                            | None                                     |
       | LCHIJA | nex                               | 2.0.8                        | NetherEx-1.12.2-2.0.8.jar                           | None                                     |
       | LCHIJA | netherportalfix                   | 5.3.17                       | NetherPortalFix_1.12.1-5.3.17.jar                   | None                                     |
       | LCHIJA | roguelike                         | 1.8.0                        | RoguelikeDungeons-1.12.2-1.8.0.jar                  | None                                     |
       | LCHIJA | stg                               | 1.12.2-1.2.3                 | stg-1.12.2-1.2.3.jar                                | None                                     |
       | LCHIJA | tatw                              | 1.0.1.2.b27                  | Tatw-1.12.2-1.0.1.2.b27.jar                         | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | thermaldynamics                   | 2.5.3                        | ThermalDynamics-1.12.2-2.5.3.16-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tp                                | 3.2.31                       | tinyprogressions-1.12.2-3.3.31-Release.jar          | None                                     |
       | LCHIJA | treechopper                       | 1.2.4                        | TreeChopper-1.12.2-1.2.4.jar                        | None                                     |
       | LCHIJA | unloader                          | 1.2.0                        | unloader-1.2.0.jar                                  | None                                     |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT              | VanillaFix-1.0.10-99.jar                            | None                                     |
       | LCHIJA | vc                                | 5.9.13                       | ViesCraft-1.12.2-5.9.13.jar                         | None                                     |
       | LCHIJA | weather2                          | 1.12.1-2.6.12                | weather2-1.12.1-2.6.12.jar                          | None                                     |
       | LCHIJA | zerocore                          | 1.12-0.1.2.2                 | zerocore-1.12-0.1.2.2.jar                           | None                                     |
       | LCHIJA | immersiveengineering              | 0.12-86                      | ImmersiveEngineering-0.12-86.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | reauth                            | 3.6.0                        | reauth-3.6.0.jar                                    | daba0ec4df71b6da841768c49fb873def208a1e3 |
  Loaded coremods (and transformers): MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b164.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      LoadingPlugin (Quark-r1.5-145.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.3347' Renderer: 'Intel(R) HD Graphics 3000'
  AE2 Version: stable rv6-stable-3 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:ON, CRAFTTWEAKER:OFF
  Suspected Mods: ModPack Basic Tools (mpbasic)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2784
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.3347, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, file/BDcraft Sounds MC113.zip, file/BDcraft Musics MC113.zip, file/PureBDcraft  64x MC113.zip, file/PureBDcraft Extra Optifine MC113.zip, file/PureBDcraft Font MC113.zip, file/PureBDcraft More 3D Blocks MC113.zip, file/PureBDcraft Noteblock English MC113.zip, file/PureBDcraft Technology MC113.zip, file/PureBDcraft More 3D Items MC113.zip, file/PureBDcraft Damaged Items MC113.zip
  Current Language: Français (Canada)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by HenrikoMagnifico** [comment]
Caused by the mod MPUtils which does not have a set configuration for the info panel shown when you start a new server. This causes the game to crash unless you set to not use the info panel in the MPUtils config.
