### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by HomemadeSoup76** [HenrikoMagnifico/YaoPack-Issue-Tracker#7]
Downloaded the Yao pack with everything fine, next time I went to play I lost all audio this happened with my friends as well

**Comment by HenrikoMagnifico** [comment]
I need more information. Does this occur only on servers? How long does it take for the sound to go away? Does it still happen on the most recent version of the Yao Pack?

**Comment by HomemadeSoup76** [comment]
It would have no audio as soon as the game was in the main menu, new patch
seems to have fixed it though
